### ISSUE TITLE
A README instruction leads to a Github 404

### ISSUE THREAD

**Issue by mgarciap** [gnosis/dx-examples-dev#1]
Following the README instructions, the section `Make sure we compile all the DutchX` says: `Check the code of the contract [here].`
The [here] link goes to the following URL which returns a 404.
https://github.com/gnosis/dx-examples-dev/blob/master/01_build-of-top-of-dx/CoolAppDependencies/CoolAppDependencies.sol

**Comment by W3stside** [comment]
fixed per your pr #2 thanks
